"use client";

import { useState } from "react";

interface Props {
    api: (path: string, options?: RequestInit) => Promise<any>;
}

type TriggerType = "command" | "cron";
type ActionType = "log" | "reply";

export default function WorkflowsTab({ api }: Props) {
    const [name, setName] = useState("");
    const [trigger, setTrigger] = useState<TriggerType>("command");
    const [triggerConfig, setTriggerConfig] = useState({ command: "", cron: "* * * * *" });
    const [action, setAction] = useState<ActionType>("reply");
    const [actionConfig, setActionConfig] = useState({ message: "Hello from OpenClaw!" });
    const [saving, setSaving] = useState(false);
    const [created, setCreated] = useState<{ path: string } | null>(null);

    function generateCode() {
        const className = name.replace(/[^a-zA-Z0-9]/g, "") || "MySkill";

        let triggerCode = "";
        let actionCode = "";

        if (trigger === "command") {
            triggerCode = `    triggers = ["${triggerConfig.command || "hello"}"];
    usage = "${triggerConfig.command || "hello"}";`;
        } else {
            triggerCode = `    // Cron job: ${triggerConfig.cron}`;
        }

        if (action === "reply") {
            actionCode = `        context.reply("${actionConfig.message}");`;
        } else {
            actionCode = `        console.log("[${className}] ${actionConfig.message}");`;
        }

        return `
/**
 * ${name} - Generated by OpenClaw Dashboard
 */
module.exports = class ${className} {
    name = "${name}";
    description = "Auto-generated workflow";
${triggerCode}

    async execute(context) {
${actionCode}
    }
};
`;
    }

    async function saveWorkflow() {
        if (!name) return alert("Please give your workflow a name");
        setSaving(true);
        const code = generateCode();

        const res = await api("/api/skills/create", {
            method: "POST",
            body: JSON.stringify({
                name,
                content: code
            })
        });

        setSaving(false);
        if (res.ok) {
            setCreated(res.data);
            setName("");
            setTriggerConfig({ command: "", cron: "* * * * *" });
        } else {
            alert(res.error || "Failed to create workflow");
        }
    }

    return (
        <div className="flex-col">
            <div className="section-header">
                <div>
                    <h2 className="section-title">⚡ Workflow Builder</h2>
                    <p className="section-subtitle">Create simple skills without writing code.</p>
                </div>
            </div>

            {created && (
                <div className="alert alert-success mb-md">
                    <span>✅</span>
                    <div>
                        <strong>Workflow Created!</strong><br />
                        Saved to: <code>{created.path}</code>.<br />
                        <em>You may need to restart the Gateway if it doesn't appear immediately.</em>
                    </div>
                    <button className="btn btn-sm btn-outline" onClick={() => setCreated(null)}>Create Another</button>
                </div>
            )}

            <div className="card">
                <div className="flex-col gap-md">
                    {/* Step 1: Name */}
                    <div className="form-group">
                        <label className="form-label">1. Name your workflow</label>
                        <input
                            className="input"
                            placeholder="e.g. Daily Greeting"
                            value={name}
                            onChange={e => setName(e.target.value)}
                        />
                    </div>

                    {/* Step 2: Trigger */}
                    <div className="form-group">
                        <label className="form-label">2. When should it run?</label>
                        <div className="flex-row gap-sm mb-sm">
                            <button className={`filter-chip ${trigger === "command" ? "active" : ""}`} onClick={() => setTrigger("command")}>💬 Command</button>
                            <button className={`filter-chip ${trigger === "cron" ? "active" : ""}`} onClick={() => setTrigger("cron")}>⏰ Schedule (Cron)</button>
                        </div>

                        {trigger === "command" ? (
                            <input
                                className="input"
                                placeholder="Command name (e.g. 'hello')"
                                value={triggerConfig.command}
                                onChange={e => setTriggerConfig({ ...triggerConfig, command: e.target.value })}
                            />
                        ) : (
                            <input
                                className="input"
                                placeholder="Cron expression (e.g. '0 9 * * *')"
                                value={triggerConfig.cron}
                                onChange={e => setTriggerConfig({ ...triggerConfig, cron: e.target.value })}
                            />
                        )}
                    </div>

                    {/* Step 3: Action */}
                    <div className="form-group">
                        <label className="form-label">3. What should it do?</label>
                        <div className="flex-row gap-sm mb-sm">
                            <button className={`filter-chip ${action === "reply" ? "active" : ""}`} onClick={() => setAction("reply")}>↩️ Reply to User</button>
                            <button className={`filter-chip ${action === "log" ? "active" : ""}`} onClick={() => setAction("log")}>📝 Log Console</button>
                        </div>

                        <input
                            className="input"
                            placeholder={action === "reply" ? "Message to send" : "Message to log"}
                            value={actionConfig.message}
                            onChange={e => setActionConfig({ ...actionConfig, message: e.target.value })}
                        />
                    </div>

                    {/* Preview */}
                    <div className="form-group">
                        <label className="form-label">Code Preview</label>
                        <pre className="code-block" style={{ maxHeight: 200, overflow: 'auto' }}>
                            {generateCode()}
                        </pre>
                    </div>

                    <div className="flex-row justify-end">
                        <button className="btn btn-primary" onClick={saveWorkflow} disabled={saving || !name}>
                            {saving ? "Creating..." : "✨ Create Workflow"}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
}
